#ifndef CONSTANTS_H
#define CONSTANTS_H

enum class CellFunctionType {
    COMPUTER,
    PROPULSION,
    SCANNER,
    WEAPON,
    CONSTRUCTOR,
    SENSOR,
    COMMUNICATOR,
    _COUNTER
};

enum class ENERGY_GUIDANCE {
    IN = 1,
    IN_VALUE_CELL = 2,
    IN_VALUE_TOKEN = 3
};
enum class ENERGY_GUIDANCE_IN {
    DEACTIVATED,
    BALANCE_CELL,
    BALANCE_TOKEN,
    BALANCE_BOTH,
    HARVEST_CELL,
    HARVEST_TOKEN
};

enum class COMMUNICATOR {
    IN = 26,
    IN_CHANNEL = 27,
    IN_MESSAGE = 28,
    IN_ANGLE = 29,
    IN_DISTANCE = 30,
    OUT_SENT_NUM_MESSAGE = 31,
    OUT_RECEIVED_NEW_MESSAGE = 32,
    OUT_RECEIVED_MESSAGE = 33,
    OUT_RECEIVED_ANGLE = 34,
    OUT_RECEIVED_DISTANCE = 35,
};
enum class COMMUNICATOR_IN {
    DO_NOTHING,
    SET_LISTENING_CHANNEL,
    SEND_MESSAGE,
    RECEIVE_MESSAGE
};
enum class COMMUNICATOR_OUT_RECEIVED_NEW_MESSAGE {
    NO,
    YES
};

#endif // CONSTANTS_H
