#include "ConstantMemory.cuh"

__constant__ GpuSettings cudaThreadSettings;
__constant__ SimulationParameters cudaSimulationParameters;
__constant__ SimulationParametersSpots cudaSimulationParametersSpots;
__constant__ FlowFieldSettings cudaFlowFieldSettings;
